name: instaflutter
description: Instaflutter Project
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.5
  firebase_core: 2.15.0
  firebase_storage: 11.2.5
  firebase_auth: 4.7.2
  firebase_messaging: 14.6.5
  cloud_functions: 4.3.4
  cloud_firestore: 4.8.4
  intl_phone_number_input: 0.7.3+1
  pin_code_fields: 8.0.1
  flutter_facebook_auth: 6.0.1
  the_apple_sign_in: 1.1.1
  easy_localization: 3.0.2
  intl: 0.18.1
  shared_preferences: 2.2.0
  flutter_native_image: 0.0.6+1
  video_compress: 3.1.2
  location: 5.0.2+1
  visibility_detector: 0.4.0+2
  google_mobile_ads: 3.0.0
  flutter_rating_bar: 4.0.1
  google_maps_flutter: 2.4.0
  image_picker: 1.0.2
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  url_launcher: 6.1.12
  cached_network_image: 3.2.3
  uuid: 3.0.7
  video_thumbnail: 0.5.3
  photo_view: 0.14.0
  http: 1.1.0
  geolocator: 9.0.2
  smooth_page_indicator: 1.1.0
  permission_handler: 10.4.3
  flutter_google_places_hoc081098: 1.2.0
  google_maps_webservice: 0.0.20-nullsafety.5
  flutter_staggered_grid_view: 0.7.0
  path_provider: 2.0.15
  provider: 6.0.5
  flutter_sound: 9.2.13
  audio_session: 0.1.16
  video_player: 2.7.0
  bloc: 8.1.2
  flutter_bloc: 8.1.3
  infinite_scroll_pagination:
  flutter_native_splash: 2.3.1
  collection: 1.18.0
  path: 1.8.3
  logger: 2.0.1
  equatable: 2.0.5

dependency_overrides:
  logger: 2.0.1
  http: 1.1.0
  visibility_detector: 0.4.0+2
  collection: 1.18.0
  intl: 0.18.1
  win32: 5.0.6

dev_dependencies:
  flutter_lints: 2.0.2
  flutter_launcher_icons: 0.13.1

flutter_native_splash:
  image: assets/images/instaflutter.png
  color: "#e1f5fe"
  color_dark: "#042a49"
  image_dark: assets/images/instaflutter.png
  android_12:
  fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/instaflutter.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/images/instaflutter.png'
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: CoreSansE
      fonts:
        - asset: assets/fonts/CoreSansE-55Medium.otf

    - family: SF-Pro-Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf